import Headings from "@/Headings"
import "bootstrap/dist/css/bootstrap.css"
import Menu from "@/Menu"
import Footer from "@/Footer"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Headings/>
        <Menu/>
        {children}
        <Footer/>
        
        </body>
    </html>
  )
}
